/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.oauth.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.oauth.model.OAuthApplicationUser;
import com.liferay.portal.oauth.model.OAuthApplicationUserModel;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the OAuthApplicationUser service. Represents a row in the &quot;OAuthApplicationUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.portal.oauth.model.OAuthApplicationUserModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OAuthApplicationUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OAuthApplicationUserImpl
 * @see com.liferay.portal.oauth.model.OAuthApplicationUser
 * @see com.liferay.portal.oauth.model.OAuthApplicationUserModel
 * @generated
 */
public class OAuthApplicationUserModelImpl extends BaseModelImpl<OAuthApplicationUser>
	implements OAuthApplicationUserModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a o auth application user model instance should use the {@link com.liferay.portal.oauth.model.OAuthApplicationUser} interface instead.
	 */
	public static final String TABLE_NAME = "OAuthApplicationUser";
	public static final Object[][] TABLE_COLUMNS = {
			{ "oaauId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "applicationId", Types.BIGINT },
			{ "accessToken", Types.VARCHAR },
			{ "accessSecret", Types.VARCHAR },
			{ "authorized", Types.BOOLEAN }
		};
	public static final String TABLE_SQL_CREATE = "create table OAuthApplicationUser (oaauId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,applicationId LONG,accessToken VARCHAR(75) null,accessSecret VARCHAR(75) null,authorized BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table OAuthApplicationUser";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.portal.oauth.model.OAuthApplicationUser"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.portal.oauth.model.OAuthApplicationUser"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.portal.oauth.model.OAuthApplicationUser"),
			true);
	public static long ACCESSTOKEN_COLUMN_BITMASK = 1L;
	public static long APPLICATIONID_COLUMN_BITMASK = 2L;
	public static long AUTHORIZED_COLUMN_BITMASK = 4L;
	public static long COMPANYID_COLUMN_BITMASK = 8L;
	public static long USERID_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.portal.oauth.model.OAuthApplicationUser"));

	public OAuthApplicationUserModelImpl() {
	}

	public long getPrimaryKey() {
		return _oaauId;
	}

	public void setPrimaryKey(long primaryKey) {
		setOaauId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_oaauId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return OAuthApplicationUser.class;
	}

	public String getModelClassName() {
		return OAuthApplicationUser.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("oaauId", getOaauId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("applicationId", getApplicationId());
		attributes.put("accessToken", getAccessToken());
		attributes.put("accessSecret", getAccessSecret());
		attributes.put("authorized", getAuthorized());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long oaauId = (Long)attributes.get("oaauId");

		if (oaauId != null) {
			setOaauId(oaauId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long applicationId = (Long)attributes.get("applicationId");

		if (applicationId != null) {
			setApplicationId(applicationId);
		}

		String accessToken = (String)attributes.get("accessToken");

		if (accessToken != null) {
			setAccessToken(accessToken);
		}

		String accessSecret = (String)attributes.get("accessSecret");

		if (accessSecret != null) {
			setAccessSecret(accessSecret);
		}

		Boolean authorized = (Boolean)attributes.get("authorized");

		if (authorized != null) {
			setAuthorized(authorized);
		}
	}

	public long getOaauId() {
		return _oaauId;
	}

	public void setOaauId(long oaauId) {
		_oaauId = oaauId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	public void setUserName(String userName) {
		_userName = userName;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getApplicationId() {
		return _applicationId;
	}

	public void setApplicationId(long applicationId) {
		_columnBitmask |= APPLICATIONID_COLUMN_BITMASK;

		if (!_setOriginalApplicationId) {
			_setOriginalApplicationId = true;

			_originalApplicationId = _applicationId;
		}

		_applicationId = applicationId;
	}

	public long getOriginalApplicationId() {
		return _originalApplicationId;
	}

	public String getAccessToken() {
		if (_accessToken == null) {
			return StringPool.BLANK;
		}
		else {
			return _accessToken;
		}
	}

	public void setAccessToken(String accessToken) {
		_columnBitmask |= ACCESSTOKEN_COLUMN_BITMASK;

		if (_originalAccessToken == null) {
			_originalAccessToken = _accessToken;
		}

		_accessToken = accessToken;
	}

	public String getOriginalAccessToken() {
		return GetterUtil.getString(_originalAccessToken);
	}

	public String getAccessSecret() {
		if (_accessSecret == null) {
			return StringPool.BLANK;
		}
		else {
			return _accessSecret;
		}
	}

	public void setAccessSecret(String accessSecret) {
		_accessSecret = accessSecret;
	}

	public boolean getAuthorized() {
		return _authorized;
	}

	public boolean isAuthorized() {
		return _authorized;
	}

	public void setAuthorized(boolean authorized) {
		_columnBitmask |= AUTHORIZED_COLUMN_BITMASK;

		if (!_setOriginalAuthorized) {
			_setOriginalAuthorized = true;

			_originalAuthorized = _authorized;
		}

		_authorized = authorized;
	}

	public boolean getOriginalAuthorized() {
		return _originalAuthorized;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			OAuthApplicationUser.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OAuthApplicationUser toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (OAuthApplicationUser)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		OAuthApplicationUserImpl oAuthApplicationUserImpl = new OAuthApplicationUserImpl();

		oAuthApplicationUserImpl.setOaauId(getOaauId());
		oAuthApplicationUserImpl.setCompanyId(getCompanyId());
		oAuthApplicationUserImpl.setUserId(getUserId());
		oAuthApplicationUserImpl.setUserName(getUserName());
		oAuthApplicationUserImpl.setCreateDate(getCreateDate());
		oAuthApplicationUserImpl.setModifiedDate(getModifiedDate());
		oAuthApplicationUserImpl.setApplicationId(getApplicationId());
		oAuthApplicationUserImpl.setAccessToken(getAccessToken());
		oAuthApplicationUserImpl.setAccessSecret(getAccessSecret());
		oAuthApplicationUserImpl.setAuthorized(getAuthorized());

		oAuthApplicationUserImpl.resetOriginalValues();

		return oAuthApplicationUserImpl;
	}

	public int compareTo(OAuthApplicationUser oAuthApplicationUser) {
		long primaryKey = oAuthApplicationUser.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		OAuthApplicationUser oAuthApplicationUser = null;

		try {
			oAuthApplicationUser = (OAuthApplicationUser)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = oAuthApplicationUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		OAuthApplicationUserModelImpl oAuthApplicationUserModelImpl = this;

		oAuthApplicationUserModelImpl._originalCompanyId = oAuthApplicationUserModelImpl._companyId;

		oAuthApplicationUserModelImpl._setOriginalCompanyId = false;

		oAuthApplicationUserModelImpl._originalUserId = oAuthApplicationUserModelImpl._userId;

		oAuthApplicationUserModelImpl._setOriginalUserId = false;

		oAuthApplicationUserModelImpl._originalApplicationId = oAuthApplicationUserModelImpl._applicationId;

		oAuthApplicationUserModelImpl._setOriginalApplicationId = false;

		oAuthApplicationUserModelImpl._originalAccessToken = oAuthApplicationUserModelImpl._accessToken;

		oAuthApplicationUserModelImpl._originalAuthorized = oAuthApplicationUserModelImpl._authorized;

		oAuthApplicationUserModelImpl._setOriginalAuthorized = false;

		oAuthApplicationUserModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<OAuthApplicationUser> toCacheModel() {
		OAuthApplicationUserCacheModel oAuthApplicationUserCacheModel = new OAuthApplicationUserCacheModel();

		oAuthApplicationUserCacheModel.oaauId = getOaauId();

		oAuthApplicationUserCacheModel.companyId = getCompanyId();

		oAuthApplicationUserCacheModel.userId = getUserId();

		oAuthApplicationUserCacheModel.userName = getUserName();

		String userName = oAuthApplicationUserCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			oAuthApplicationUserCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			oAuthApplicationUserCacheModel.createDate = createDate.getTime();
		}
		else {
			oAuthApplicationUserCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			oAuthApplicationUserCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			oAuthApplicationUserCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		oAuthApplicationUserCacheModel.applicationId = getApplicationId();

		oAuthApplicationUserCacheModel.accessToken = getAccessToken();

		String accessToken = oAuthApplicationUserCacheModel.accessToken;

		if ((accessToken != null) && (accessToken.length() == 0)) {
			oAuthApplicationUserCacheModel.accessToken = null;
		}

		oAuthApplicationUserCacheModel.accessSecret = getAccessSecret();

		String accessSecret = oAuthApplicationUserCacheModel.accessSecret;

		if ((accessSecret != null) && (accessSecret.length() == 0)) {
			oAuthApplicationUserCacheModel.accessSecret = null;
		}

		oAuthApplicationUserCacheModel.authorized = getAuthorized();

		return oAuthApplicationUserCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{oaauId=");
		sb.append(getOaauId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", applicationId=");
		sb.append(getApplicationId());
		sb.append(", accessToken=");
		sb.append(getAccessToken());
		sb.append(", accessSecret=");
		sb.append(getAccessSecret());
		sb.append(", authorized=");
		sb.append(getAuthorized());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.liferay.portal.oauth.model.OAuthApplicationUser");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>oaauId</column-name><column-value><![CDATA[");
		sb.append(getOaauId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicationId</column-name><column-value><![CDATA[");
		sb.append(getApplicationId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>accessToken</column-name><column-value><![CDATA[");
		sb.append(getAccessToken());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>accessSecret</column-name><column-value><![CDATA[");
		sb.append(getAccessSecret());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>authorized</column-name><column-value><![CDATA[");
		sb.append(getAuthorized());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = OAuthApplicationUser.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			OAuthApplicationUser.class
		};
	private long _oaauId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userUuid;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private long _applicationId;
	private long _originalApplicationId;
	private boolean _setOriginalApplicationId;
	private String _accessToken;
	private String _originalAccessToken;
	private String _accessSecret;
	private boolean _authorized;
	private boolean _originalAuthorized;
	private boolean _setOriginalAuthorized;
	private long _columnBitmask;
	private OAuthApplicationUser _escapedModelProxy;
}